default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: << YOUR POSTGRESQL USERNAME HERE >>
  password: << YOUR POSTGRESQL PASSWORD HERE >>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test
